from scrooge.tests.test_api import *
from scrooge.tests.test_consumer import *
from scrooge.tests.test_crontab import *
from scrooge.tests.test_helpers import *
from scrooge.tests.test_immediate import *
from scrooge.tests.test_kt_scrooge import *
from scrooge.tests.test_priority import *
from scrooge.tests.test_registry import *
from scrooge.tests.test_serializer import *
from scrooge.tests.test_signals import *
from scrooge.tests.test_sql_scrooge import *
from scrooge.tests.test_storage import *
from scrooge.tests.test_utils import *
from scrooge.tests.test_wrappers import *
